language: cpp

compiler:
  - gcc
  
after_success:
  - bin/hiredis-happ-test
  
script: 
  - REPO_DIR=$PWD
  - mkdir -p tools && cd tools
  - CMAKE_PREFIX=$HOME/prebuilt;
  - if [ ! -e "$CMAKE_PREFIX/bin/cmake" ]; then
        wget -c "https://github.com/Kitware/CMake/archive/v3.2.3.tar.gz" ;
        tar -axvf v3.2.3.tar.gz  > build_cmake.log 2>&1 ;
        cd CMake-3.2.3 ;
        ./bootstrap --prefix=$CMAKE_PREFIX  >> build_cmake.log 2>&1 ;
        make -j4 install  >> build_cmake.log 2>&1 ;
    fi
  - mkdir -p $REPO_DIR/build && cd $REPO_DIR/build ;
  - env LD_LIBRARY_PATH=$CMAKE_PREFIX/lib C_INCLUDE_PATH=$CMAKE_PREFIX/include CXX_INCLUDE_PATH=$CMAKE_PREFIX/include $CMAKE_PREFIX/bin/cmake .. ;
  - make -j4 ;
  - if [ -e "$REPO_DIR/build/prebuilt" ]; then
        cp -rf "$REPO_DIR/build/prebuilt"/*/* "$CMAKE_PREFIX";
    fi

install: true

cache: 
    apt: true
    directories:
    - $CMAKE_PREFIX
    
branches:
  only:
    - master

notifications:
  email: false
  irc:
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"

env:
  - LANG="zh_CN.UTF-8"

os:
  - linux
  - osx

osx_image: xcode61
