language: cpp

env:
  global:
    - LANG="zh_CN.UTF-8"
    - CMAKE_PREFIX=$HOME/prebuilt/cmake
    - CMAKE_URL=https://cmake.org/files/v3.9/cmake-3.9.3-Linux-x86_64.sh
    - CMAKE_BIN=$HOME/prebuilt/cmake/bin/cmake

matrix:
  include:
    - os: osx
      env: USE_CC=clang USE_CXX=clang++
    - os: osx
      env: USE_CC=gcc USE_CXX=g++
    - os: linux
      dist: trusty
      sudo: false
      env: USE_CC=gcc USE_CXX=g++
    - os: linux
      dist: trusty
      sudo: false
      env: USE_CC=gcc-4.4 USE_CXX=g++-4.4
    - os: linux
      dist: trusty
      sudo: false
      env: USE_CC=gcc-4.9 USE_CXX=g++-4.9
    - os: linux
      dist: trusty
      sudo: false
      env: USE_CC=gcc-7 USE_CXX=g++-7
    #- os: linux
    #  dist: trusty
    #  sudo: false
    #  env: USE_CC=clang USE_CXX=clang++
    # - os: linux
    #   dist: trusty
    #   sudo: false
    #   env: USE_CC=clang-3.8 USE_CXX=clang++-3.8

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
      #- sourceline: 'ppa:george-edison55/cmake-3.x'
      #  key_url: null
      # - sourceline: 'deb http://apt.llvm.org/trusty/ llvm-toolchain-trusty-3.8 main'
      #   key_url: 'http://apt.llvm.org/llvm-snapshot.gpg.key'

    packages:
      - g++-4.4
      - g++-4.4-multilib
      - gcc-4.4
      - gcc-4.4-multilib
      - gcc-4.9
      - gcc-4.9-multilib
      - g++-4.9
      - g++-4.9-multilib
      - gcc-7
      - gcc-7-multilib
      - g++-7
      - g++-7-multilib
      - clang
      ## - libc++1
      ## - libc++-dev
      ## - libc++abi1
      ## - libc++abi-dev
      # - clang-3.8
      # - libclang-common-3.8-dev
      # - libclang-3.8-dev

before_install:
  # - if [ "$TRAVIS_OS_NAME" == "linux" ]; then apt-get -qq -y update; fi # sudo: false can not install package through apt-get
  - if [ "$TRAVIS_OS_NAME" == "osx" ]; then brew update; brew upgrade cmake; fi

install: >-
    if [ "$TRAVIS_OS_NAME" == "linux" ]; then

      if [ ! -e "$CMAKE_BIN" ]; then

        curl -L --insecure "$CMAKE_URL" -o "cmake-Linux-x86_64.sh";

        sh cmake-Linux-x86_64.sh --prefix=$CMAKE_PREFIX --skip-license ;

      fi

    fi

    if [ "$TRAVIS_OS_NAME" == "osx" ]; then 

      brew upgrade cmake; 

      brew install --HEAD libuv; 

      export CMAKE_BIN=$(which cmake); 

    fi

after_success:
  - test/hiredis-happ-test
  
script: 
  - export CC=$USE_CC
  - export CXX=$USE_CXX
  - REPO_DIR=$PWD;
  - mkdir -p tools && cd tools
  - mkdir -p $REPO_DIR/build && cd $REPO_DIR/build ;
  - echo "$CMAKE_BIN .. -DPROJECT_ENABLE_UNITTEST=ON -DPROJECT_ENABLE_SAMPLE=ON -DCMAKE_C_COMPILER=$USE_CC -DCMAKE_CXX_COMPILER=$USE_CXX" ;
  - $CMAKE_BIN .. -DPROJECT_ENABLE_UNITTEST=ON -DPROJECT_ENABLE_SAMPLE=ON -DCMAKE_C_COMPILER=$USE_CC -DCMAKE_CXX_COMPILER=$USE_CXX ;
  - make -j4 ;

cache: 
    apt: true
    ccache: true
    directories:
    - $CMAKE_PREFIX
    
branches:
  only:
    - master

notifications:
  email: false
  irc:
    template:
      - "%{repository}/%{branch} (%{commit} - %{author}): %{build_url}: %{message}"
