#
# Appveyor configuration file for CI build of hiredis-happ on Windows (under Cygwin)
#
# For further details see http://www.appveyor.com
#

#
# Custom environment variables
#
environment:
    global:
        CYG_ROOT: C:/cygwin64
        CYG_MIRROR: http://cygwin.mirror.constant.com
        CYG_CACHE: C:/cygwin64/var/cache/setup
        CYG_BASH: C:/cygwin64/bin/bash.exe

#
# Cache Cygwin files to speed up build
#
cache:
    - '%CYG_CACHE%'

#
# Do a shallow clone of the repo to speed up build
#
clone_depth: 1

#
# Initialisation prior to pulling the Mono repository
# Attempt to ensure we don't try to convert line endings to Win32 CRLF as this will cause build to fail
#
init:
    - git config --global core.autocrlf input

#
# Install needed build dependencies
# 
install:
    - set
    - ps: |
        Start-FileDownload "http://cygwin.com/setup-x86_64.exe" -FileName "setup-x86_64.exe"

        echo "Installing cygwin64"

        Invoke-Expression -Command ".\setup-x86_64.exe --wait --quiet-mode --no-shortcuts --only-site --root '$env:CYG_ROOT' --site '$env:CYG_MIRROR' --local-package-dir '$env:CYG_CACHE' --upgrade-also --packages 'autoconf,automake,bison,gcc-core,gcc-g++,libtool,make,python,gettext-devel,gettext,intltool,libiconv,pkg-config,git,curl,wget,cmake,libevent-devel'"

        Invoke-Expression -Command "$env:CYG_BASH -lc 'cygcheck -dc cygwin cmake gcc-g++'"

# Cygwin build script
#
# NOTES:
#
# The stdin/stdout file descriptor appears not to be valid for the Appveyor
# build which causes failures as certain functions attempt to redirect 
# default file handles. Ensure a dummy file descriptor is opened with 'exec'.
#
build_script:
    - ps: |
        $CYGWIN_DIR=$env:APPVEYOR_BUILD_FOLDER -Replace "\\","/"

        echo "Building... $env:CYG_BASH -lc 'cd ""$CYGWIN_DIR""; pwd; mkdir -p build; cd build; cmake .. -DPROJECT_ENABLE_UNITTEST=ON -DPROJECT_ENABLE_SAMPLE=ON && make -j4;'"

        Invoke-Expression -Command "$env:CYG_BASH -lc 'cd ""$CYGWIN_DIR""; pwd; mkdir -p build; cd build; cmake .. -DPROJECT_ENABLE_UNITTEST=ON -DPROJECT_ENABLE_SAMPLE=ON && make -j4;'"
#
# Run unit test
# 
test_script:
    - ps: |
        $CYGWIN_DIR=$env:APPVEYOR_BUILD_FOLDER -Replace "\\","/"

        Invoke-Expression -Command "$env:CYG_BASH -lc 'cd ""$CYGWIN_DIR""; pwd; build/test/hiredis-happ-test'"

#
# Only build the master branch
#
branches:
  only:
    - master

# no need artifacts
